---
title: "Predictive Modeling of Mouse Decision Outcomes from Visual Cortex Spike Trains"
author: "Rocco Del Toro ID: 921304225"
date: "2025-03-17"
output: html_document
---

# Abstract

Decision making in the brain is an intricate process involving the combination of sensory activation, neural connectivity, and motor response. In the following project, we analyze a portion of data from Nicholas A. Steinmetz et al.(2019), who led a research question on neural activity data collected from visual cortex recordings of mice in a decision making task. Of the 10 mice and 39 sessions included in the study, we're magnifying in on only 18 sessions (1-18) and four mice: Cori, Frossman, Hence, and Lederberg. These mice were presented with stimuli of varying contrasts on two screens and were required to make decisions based on the stimuli using a paw-controlled wheel. Therefore, the primary goal of this project is to engineer a predictive model based on the neural spike train data and stimulus conditions to forecast success or failure in each trial. In order to achieve this goal, the analysis is divided intro three parts: Exploratory Data Analysis (EDA), Data Integration, and Predictive modeling. The first part, EDA, focuses on understanding the characteristics of the data sets, examining neural patterns through visualizations, and identifying key variability across the 18 sessions. Section two, Data integration, will involve pre-processing spike train data through normalization, clustering, and dimensional reduction to extract insights. Lastly, predictive modeling employees data science and machine learning techniques such as logistic regression to predict trial outcomes on the test sets from two sessions. The findings from this project aim to provide both predictive accuracy as well as a greater understanding of neural mechanisms and their role in establishing decisions. 

# 1. Introduction

## 1.1 Scientific Context

The influence of sensory information and brain processes to guide direct behavior has been a fundamental question in the field of neuroscience. Recent studies such as that of Steinmetz et al. (2019) have investigated just that, analyzing distributed neural activity across various brain regions in mice during complex tasks. Across each session and trial, mice observed visual stimuli at varying contrast levels on two screens and made decisions through the use of a fore-paw wheel. Utilizing Neuropixels probes, the researchers documented spike trains from approximately 30,000 neurons across 42 brain regions during the success or failure of each task. Principle findings from the study included: neurons encoding choice related signals were confined in certain brain regions such as the visual cortex and mid-brain, neural activity patterns before stimulus onset predicted the task engagement, and lastly signals related to action were distributed across all regions of the brain. 

This project will hone in on spike train recordings from the visual cortex during 18 sessions (1 - 18) involving four mice. The main goal it to develop a predictive model that classifies trial success, or failure, using the spike train outcomes and stimulus contrast conditions. Through the use of statistical data science methodology, we aim to uncover patterns in neural activity and hopefully broaden our understanding of how neural sense is translated into action.

## 1.2 Statistical Obstacles

The nature of the data set presents several challenges making the production of a predictive model a complex problem. 
1. Each trial contains documentation from over 1,0000 neurons in 40 time bins (e.g. 1077 by 40 matrix), resulting in a high-dimensional feature space prone to over fitting 2. There is an imbalance in terms of success or failure across trials, may not be evenly distributed which could possibly result in bias of a predictive model 3. Neural activity can evolve with time which creates temporal dependencies, requiring the capture of relevant information and the reduction of white noise 4. There are differences in individual mice and sessions which present possible heterogeneity and disruptions in model generalization. 






## 1.3 Questions & Hypotheses














```{r appendix, echo=FALSE, results='asis'}
knitr::all_code()
```






